### ISSUE TITLE
Miss internal nav in the recently added mastery section

### ISSUE THREAD

**Issue by Lux-source** [dcbuild3r/devpill.me#28]
## Description

Missing 'internal nav section' on the righ side  ###ON THIS PAGE.

### Steps to reproduce

Check it out in this links: https://www.devpill.me/docs/mastery/notetaking/
https://www.devpill.me/docs/mastery/mentorship/
https://www.devpill.me/docs/mastery/time-management/

### Expected result

We should be able to see  the internal nav bar of the section like in this one: 
https://www.devpill.me/docs/mastery/learn-to-learn/

**Comment by dcbuild3r** [comment]
Thanks for noticing, I'll try and take a look. This repo is using a HUGO theme called Doks, so I might not be able to help too much. devpill.me will be migrating to a different platform once it's live anyways, so if it doesn't work now, it will on the other one

**Comment by dcbuild3r** [comment]
The issue is using Markdown Heading 4+. The navbar only gets created for Heading 1-3. I'll keep it in mind for other sections and clean it up once I have the time so that the navbar gets created correctly.
