### ISSUE TITLE
Proofreading feedback

### ISSUE THREAD

**Issue by csggene3** [dcbuild3r/devpill.me#52]
## Description

I noticed on the foreword that you indicated proofreading was something you would seek out from others. I noticed at least one typo, and wanted to reach out and ask if I could be of service in helping proofread further.

### Steps to reproduce

The bottom of the front page uses available twice inappropriately. It's an easy oversight to make when building something so large.

### Expected result

n/a

### Actual result

n/a

### Environment

n/a

**Comment by dcbuild3r** [comment]
hey. I'll migrate the content to another platform once it's ready and there are people that will proofread what is on devpill. Thanks for your offer :)
